version: '3.7'
services:
  mariadb:
    image: mariadb
    container_name: ratkerDevMaria
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: RatkerDev
      MYSQL_USER: tester
      MYSQL_PASSWORD: password
    ports:
      - "23306:3306"
    volumes:
      - ratker-db-volume:/var/lib/mysql

volumes:
  ratker-db-volume: